CREATE TABLE IF NOT EXISTS AUTHOR (
    id INTEGER PRIMARY KEY,
    first_name VARCHAR(120) NOT NULL,
    last_name VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS ARTICLES (
    id INTEGER PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    id_author INTEGER,
    CONSTRAINT fk_id_author FOREIGN KEY (id_author) REFERENCES AUTHOR(id)
);